name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the coordinate_parser Docker image
      run: docker build . --file coordinate_parser/Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Build the grant_parser Docker image
      run: docker build . --file grant_parser/Dockerfile --tag my-image-name:$(date +%s)
